canonical: https://gematik.de/fhir/isik/v3/VitalparameterUndKoerpermasze
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
dependencies:
  de.basisprofil.r4: 1.5.0-alpha6
  de.gematik.isik-basismodul: 3.0.0