canonical: https://gematik.de/fhir/isik/v3/VitalwerteUndKoerpermasse
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: Implementierungsleitfaden ISiK-Modul Vitalwerte und Körpermaße
name: Implementierungsleitfaden ISiK-Modul Vitalwerte und Körpermaße
status: draft
dependencies:
  de.basisprofil.r4: 1.4.0
  de.gematik.isik-basismodul: 3.0.0-rc2
